name: Lint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches: [master]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format check
        run: ruff format --check .
